title: aplutop
author: lywszh
email: lywszh@vip.qq.com
description: > # this means to ignore newlines until "baseurl:"
  the page for apluto.

# social links
# twitter_username: your-twitter-handle
github_username:  lywszh

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
